services:

  prometheus-test:
    image: prom/prometheus:v3.5.0
    container_name: prometheus-test
    restart: unless-stopped

    ports:
      - "9190:9090"

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=7d"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data/prometheus:/prometheus

    networks:
      - monitoring-test


  grafana-test:
    image: grafana/grafana-oss:12.1.1
    container_name: grafana-test
    restart: unless-stopped

    depends_on:
      - prometheus-test

    ports:
      - "3300:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"

    volumes:
      - ./data/grafana:/var/lib/grafana

    networks:
      - monitoring-test


  node-exporter-test:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter-test
    restart: unless-stopped

    ports:
      - "9110:9100"

    networks:
      - monitoring-test


networks:

  monitoring-test:
    driver: bridge
